return {
  -- 'akinsho/bufferline.nvim',
  -- version = '*',
  -- dependencies = 'nvim-tree/nvim-web-devicons',
  -- config = function()
  --   vim.opt.termguicolors = true
  --   require('bufferline').setup {
  --     options = {
  --       separator_style = 'slant',
  --       indicator = {
  --         style = 'underline',
  --       },
  --       offsets = {
  --         {
  --           filetype = 'neo-tree',
  --           text = 'File Explorer',
  --           highlight = 'Directory',
  --           separator = true, -- use a "true" to enable the default, or set your own character
  --         },
  --       },
  --       groups = {
  --         items = {
  --           require('bufferline.groups').builtin.pinned:with { icon = '󰐃 ' },
  --         },
  --       },
  --     },
  --   }
  -- end,
}
